### ISSUE TITLE
Add “secure” flag to stop privilege escalation

### ISSUE THREAD

**Issue by nicksantamaria** [previousnext/skpr#36]

**Comment by nicksantamaria** [comment]
```yml
apiVersion: v1
kind: Pod
metadata:
  name: myPod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
```
